name: permission_checker
description: "This package should make it easier for developers to interact with native permissions, since there are many different permissions that relate to a single entity, such as access to photos on different versions of operating systems."
version: 0.0.1
homepage: "https://pub.dev/packages/permission_checker"

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  device_info_plus: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
